//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insigma.Eyes.PSS.WinUI.BLLCustomer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLLCustomer.ICustomerManagerService")]
    public interface ICustomerManagerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagerService/GetCustomers", ReplyAction="http://tempuri.org/ICustomerManagerService/GetCustomersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/ICustomerManagerService/GetCustomersExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        Insigma.Eyes.PSS.Model.CustomerModel[] GetCustomers(string name, string tel, string address, string remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagerService/GetCustomersByCondition", ReplyAction="http://tempuri.org/ICustomerManagerService/GetCustomersByConditionResponse")]
        Insigma.Eyes.PSS.Model.CustomerModel[] GetCustomersByCondition(string condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagerService/GetOneCustomer", ReplyAction="http://tempuri.org/ICustomerManagerService/GetOneCustomerResponse")]
        Insigma.Eyes.PSS.Model.CustomerModel GetOneCustomer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagerService/AddCustomer", ReplyAction="http://tempuri.org/ICustomerManagerService/AddCustomerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/ICustomerManagerService/AddCustomerExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        Insigma.Eyes.PSS.Model.CustomerModel AddCustomer(Insigma.Eyes.PSS.Model.CustomerModel oneCommodity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerManagerService/UpdateCustomer", ReplyAction="http://tempuri.org/ICustomerManagerService/UpdateCustomerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/ICustomerManagerService/UpdateCustomerExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool UpdateCustomer(Insigma.Eyes.PSS.Model.CustomerModel commodity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerManagerServiceChannel : Insigma.Eyes.PSS.WinUI.BLLCustomer.ICustomerManagerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerManagerServiceClient : System.ServiceModel.ClientBase<Insigma.Eyes.PSS.WinUI.BLLCustomer.ICustomerManagerService>, Insigma.Eyes.PSS.WinUI.BLLCustomer.ICustomerManagerService {
        
        public CustomerManagerServiceClient() {
        }
        
        public CustomerManagerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerManagerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerManagerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerManagerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Insigma.Eyes.PSS.Model.CustomerModel[] GetCustomers(string name, string tel, string address, string remark) {
            return base.Channel.GetCustomers(name, tel, address, remark);
        }
        
        public Insigma.Eyes.PSS.Model.CustomerModel[] GetCustomersByCondition(string condition) {
            return base.Channel.GetCustomersByCondition(condition);
        }
        
        public Insigma.Eyes.PSS.Model.CustomerModel GetOneCustomer(int id) {
            return base.Channel.GetOneCustomer(id);
        }
        
        public Insigma.Eyes.PSS.Model.CustomerModel AddCustomer(Insigma.Eyes.PSS.Model.CustomerModel oneCommodity) {
            return base.Channel.AddCustomer(oneCommodity);
        }
        
        public bool UpdateCustomer(Insigma.Eyes.PSS.Model.CustomerModel commodity) {
            return base.Channel.UpdateCustomer(commodity);
        }
    }
}
