//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insigma.Eyes.PSS.WinUI.BLLSalesOrders {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLLSalesOrders.ISalesManagerService")]
    public interface ISalesManagerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManagerService/GetSalesOrders", ReplyAction="http://tempuri.org/ISalesManagerService/GetSalesOrdersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/ISalesManagerService/GetSalesOrdersExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        Insigma.Eyes.PSS.Model.SalesOrdersModel[] GetSalesOrders(string orderNumber, string orderDateStart, string orderDateEnd, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManagerService/GetSalesCommoditiesByID", ReplyAction="http://tempuri.org/ISalesManagerService/GetSalesCommoditiesByIDResponse")]
        Insigma.Eyes.PSS.Model.SalesCommodityModel[] GetSalesCommoditiesByID(int salesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManagerService/AddSalesOrder", ReplyAction="http://tempuri.org/ISalesManagerService/AddSalesOrderResponse")]
        Insigma.Eyes.PSS.Model.SalesOrdersModel AddSalesOrder(Insigma.Eyes.PSS.Model.SalesOrdersModel salesOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManagerService/UpdateCommodity", ReplyAction="http://tempuri.org/ISalesManagerService/UpdateCommodityResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/ISalesManagerService/UpdateCommodityExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool UpdateCommodity(Insigma.Eyes.PSS.Model.SalesCommodityModel commodity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManagerService/GetOneSalesCommodityByID", ReplyAction="http://tempuri.org/ISalesManagerService/GetOneSalesCommodityByIDResponse")]
        Insigma.Eyes.PSS.Model.SalesCommodityModel GetOneSalesCommodityByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManagerService/AddSalesCommodity", ReplyAction="http://tempuri.org/ISalesManagerService/AddSalesCommodityResponse")]
        Insigma.Eyes.PSS.Model.SalesCommodityModel AddSalesCommodity(Insigma.Eyes.PSS.Model.SalesCommodityModel oneSalesCommodity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManagerService/DeleteSalesCommoditiesBySalesOrderID", ReplyAction="http://tempuri.org/ISalesManagerService/DeleteSalesCommoditiesBySalesOrderIDRespo" +
            "nse")]
        bool DeleteSalesCommoditiesBySalesOrderID(int salesOrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManagerService/UpdateSalesOrder", ReplyAction="http://tempuri.org/ISalesManagerService/UpdateSalesOrderResponse")]
        bool UpdateSalesOrder(Insigma.Eyes.PSS.Model.SalesOrdersModel oneSalesOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManagerService/PostSalesOrder", ReplyAction="http://tempuri.org/ISalesManagerService/PostSalesOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/ISalesManagerService/PostSalesOrderExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool PostSalesOrder(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManagerService/GetOneSalesOrder", ReplyAction="http://tempuri.org/ISalesManagerService/GetOneSalesOrderResponse")]
        Insigma.Eyes.PSS.Model.SalesOrdersModel GetOneSalesOrder(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManagerService/DeleteSalesCommodity", ReplyAction="http://tempuri.org/ISalesManagerService/DeleteSalesCommodityResponse")]
        bool DeleteSalesCommodity(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesManagerService/DeleteOrderID", ReplyAction="http://tempuri.org/ISalesManagerService/DeleteOrderIDResponse")]
        bool DeleteOrderID(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalesManagerServiceChannel : Insigma.Eyes.PSS.WinUI.BLLSalesOrders.ISalesManagerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesManagerServiceClient : System.ServiceModel.ClientBase<Insigma.Eyes.PSS.WinUI.BLLSalesOrders.ISalesManagerService>, Insigma.Eyes.PSS.WinUI.BLLSalesOrders.ISalesManagerService {
        
        public SalesManagerServiceClient() {
        }
        
        public SalesManagerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesManagerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesManagerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesManagerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Insigma.Eyes.PSS.Model.SalesOrdersModel[] GetSalesOrders(string orderNumber, string orderDateStart, string orderDateEnd, string status) {
            return base.Channel.GetSalesOrders(orderNumber, orderDateStart, orderDateEnd, status);
        }
        
        public Insigma.Eyes.PSS.Model.SalesCommodityModel[] GetSalesCommoditiesByID(int salesID) {
            return base.Channel.GetSalesCommoditiesByID(salesID);
        }
        
        public Insigma.Eyes.PSS.Model.SalesOrdersModel AddSalesOrder(Insigma.Eyes.PSS.Model.SalesOrdersModel salesOrder) {
            return base.Channel.AddSalesOrder(salesOrder);
        }
        
        public bool UpdateCommodity(Insigma.Eyes.PSS.Model.SalesCommodityModel commodity) {
            return base.Channel.UpdateCommodity(commodity);
        }
        
        public Insigma.Eyes.PSS.Model.SalesCommodityModel GetOneSalesCommodityByID(int id) {
            return base.Channel.GetOneSalesCommodityByID(id);
        }
        
        public Insigma.Eyes.PSS.Model.SalesCommodityModel AddSalesCommodity(Insigma.Eyes.PSS.Model.SalesCommodityModel oneSalesCommodity) {
            return base.Channel.AddSalesCommodity(oneSalesCommodity);
        }
        
        public bool DeleteSalesCommoditiesBySalesOrderID(int salesOrderID) {
            return base.Channel.DeleteSalesCommoditiesBySalesOrderID(salesOrderID);
        }
        
        public bool UpdateSalesOrder(Insigma.Eyes.PSS.Model.SalesOrdersModel oneSalesOrder) {
            return base.Channel.UpdateSalesOrder(oneSalesOrder);
        }
        
        public bool PostSalesOrder(int id) {
            return base.Channel.PostSalesOrder(id);
        }
        
        public Insigma.Eyes.PSS.Model.SalesOrdersModel GetOneSalesOrder(int id) {
            return base.Channel.GetOneSalesOrder(id);
        }
        
        public bool DeleteSalesCommodity(int id) {
            return base.Channel.DeleteSalesCommodity(id);
        }
        
        public bool DeleteOrderID(int id) {
            return base.Channel.DeleteOrderID(id);
        }
    }
}
