//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insigma.Eyes.PSS.WinUI.BLLPurchaseOrders {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLLPurchaseOrders.IPurchaseManagerService")]
    public interface IPurchaseManagerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseManagerService/GetPurchaseOrders", ReplyAction="http://tempuri.org/IPurchaseManagerService/GetPurchaseOrdersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IPurchaseManagerService/GetPurchaseOrdersExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        Insigma.Eyes.PSS.Model.PurchaseOrdersModel[] GetPurchaseOrders(string orderNumber, string orderDateStart, string orderDateEnd, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseManagerService/GetPurchaseCommoditiesByID", ReplyAction="http://tempuri.org/IPurchaseManagerService/GetPurchaseCommoditiesByIDResponse")]
        Insigma.Eyes.PSS.Model.PurchaseCommodityModel[] GetPurchaseCommoditiesByID(int purchaseID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseManagerService/GetOnePurchaseCommoditiesByID", ReplyAction="http://tempuri.org/IPurchaseManagerService/GetOnePurchaseCommoditiesByIDResponse")]
        Insigma.Eyes.PSS.Model.PurchaseCommodityModel GetOnePurchaseCommoditiesByID(int purchaseCommodityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseManagerService/UpdatePurchaseCommodity", ReplyAction="http://tempuri.org/IPurchaseManagerService/UpdatePurchaseCommodityResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IPurchaseManagerService/UpdatePurchaseCommodityExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool UpdatePurchaseCommodity(Insigma.Eyes.PSS.Model.PurchaseCommodityModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseManagerService/AddPurchaseCommodityModel", ReplyAction="http://tempuri.org/IPurchaseManagerService/AddPurchaseCommodityModelResponse")]
        Insigma.Eyes.PSS.Model.PurchaseCommodityModel AddPurchaseCommodityModel(Insigma.Eyes.PSS.Model.PurchaseCommodityModel onePurchaseCommodity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseManagerService/PostPurchaseOrder", ReplyAction="http://tempuri.org/IPurchaseManagerService/PostPurchaseOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IPurchaseManagerService/PostPurchaseOrderExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool PostPurchaseOrder(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseManagerService/GetOnePurchaseOrder", ReplyAction="http://tempuri.org/IPurchaseManagerService/GetOnePurchaseOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IPurchaseManagerService/GetOnePurchaseOrderExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        Insigma.Eyes.PSS.Model.PurchaseOrdersModel GetOnePurchaseOrder(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseManagerService/DeletePurchaseCommodity", ReplyAction="http://tempuri.org/IPurchaseManagerService/DeletePurchaseCommodityResponse")]
        bool DeletePurchaseCommodity(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseManagerService/AddPurchaseOrder", ReplyAction="http://tempuri.org/IPurchaseManagerService/AddPurchaseOrderResponse")]
        Insigma.Eyes.PSS.Model.PurchaseOrdersModel AddPurchaseOrder(Insigma.Eyes.PSS.Model.PurchaseOrdersModel purchaseOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseManagerService/UpdatePurchaseOrder", ReplyAction="http://tempuri.org/IPurchaseManagerService/UpdatePurchaseOrderResponse")]
        bool UpdatePurchaseOrder(Insigma.Eyes.PSS.Model.PurchaseOrdersModel onePurchaseOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseManagerService/DeletePurchaseCommoditiesByPurchaseOrd" +
            "erID", ReplyAction="http://tempuri.org/IPurchaseManagerService/DeletePurchaseCommoditiesByPurchaseOrd" +
            "erIDResponse")]
        bool DeletePurchaseCommoditiesByPurchaseOrderID(int purchaseOrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseManagerService/DeleteOrderID", ReplyAction="http://tempuri.org/IPurchaseManagerService/DeleteOrderIDResponse")]
        bool DeleteOrderID(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPurchaseManagerServiceChannel : Insigma.Eyes.PSS.WinUI.BLLPurchaseOrders.IPurchaseManagerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurchaseManagerServiceClient : System.ServiceModel.ClientBase<Insigma.Eyes.PSS.WinUI.BLLPurchaseOrders.IPurchaseManagerService>, Insigma.Eyes.PSS.WinUI.BLLPurchaseOrders.IPurchaseManagerService {
        
        public PurchaseManagerServiceClient() {
        }
        
        public PurchaseManagerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchaseManagerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseManagerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseManagerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Insigma.Eyes.PSS.Model.PurchaseOrdersModel[] GetPurchaseOrders(string orderNumber, string orderDateStart, string orderDateEnd, string status) {
            return base.Channel.GetPurchaseOrders(orderNumber, orderDateStart, orderDateEnd, status);
        }
        
        public Insigma.Eyes.PSS.Model.PurchaseCommodityModel[] GetPurchaseCommoditiesByID(int purchaseID) {
            return base.Channel.GetPurchaseCommoditiesByID(purchaseID);
        }
        
        public Insigma.Eyes.PSS.Model.PurchaseCommodityModel GetOnePurchaseCommoditiesByID(int purchaseCommodityID) {
            return base.Channel.GetOnePurchaseCommoditiesByID(purchaseCommodityID);
        }
        
        public bool UpdatePurchaseCommodity(Insigma.Eyes.PSS.Model.PurchaseCommodityModel model) {
            return base.Channel.UpdatePurchaseCommodity(model);
        }
        
        public Insigma.Eyes.PSS.Model.PurchaseCommodityModel AddPurchaseCommodityModel(Insigma.Eyes.PSS.Model.PurchaseCommodityModel onePurchaseCommodity) {
            return base.Channel.AddPurchaseCommodityModel(onePurchaseCommodity);
        }
        
        public bool PostPurchaseOrder(int id) {
            return base.Channel.PostPurchaseOrder(id);
        }
        
        public Insigma.Eyes.PSS.Model.PurchaseOrdersModel GetOnePurchaseOrder(int id) {
            return base.Channel.GetOnePurchaseOrder(id);
        }
        
        public bool DeletePurchaseCommodity(int id) {
            return base.Channel.DeletePurchaseCommodity(id);
        }
        
        public Insigma.Eyes.PSS.Model.PurchaseOrdersModel AddPurchaseOrder(Insigma.Eyes.PSS.Model.PurchaseOrdersModel purchaseOrder) {
            return base.Channel.AddPurchaseOrder(purchaseOrder);
        }
        
        public bool UpdatePurchaseOrder(Insigma.Eyes.PSS.Model.PurchaseOrdersModel onePurchaseOrder) {
            return base.Channel.UpdatePurchaseOrder(onePurchaseOrder);
        }
        
        public bool DeletePurchaseCommoditiesByPurchaseOrderID(int purchaseOrderID) {
            return base.Channel.DeletePurchaseCommoditiesByPurchaseOrderID(purchaseOrderID);
        }
        
        public bool DeleteOrderID(int id) {
            return base.Channel.DeleteOrderID(id);
        }
    }
}
